name: Rust

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: taiki-e/install-action@just
    - uses: actions/checkout@v4
    - name: Install libmnl-dev
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y libmnl-dev
    - name: Build
      run: just package
