name: Rust

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform_suffix: 'linux'
            exe_suffix: ''
          - os: windows-latest
            platform_suffix: 'windows'
            exe_suffix: '.exe'

    steps:
    - uses: taiki-e/install-action@just
    - uses: actions/checkout@v4
    - name: Install libmnl-dev
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y libmnl-dev
    - name: Install libnftnl-dev
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install -y libnftnl-dev
    - name: Build
      run: just package
    - name: Rename Artifact
      run: mv target/production/ow2-server-picker${{matrix.exe_suffix}} ow2-server-picker-${{matrix.platform_suffix}}${{matrix.exe_suffix}}
    - uses: softprops/action-gh-release@v2
      with:
        files: ow2-server-picker-${{matrix.platform_suffix}}${{matrix.exe_suffix}}
